- name: Install tools
  action: apt pkg={{ item.name }} state=installed
  with_items: 
  - { name: python-dev }
  - { name: python-pip }
  - { name: git }

- name: Checkout Skyline 
  action: git repo={{ skyline.repo }} dest={{ skyline.path }} version={{ skyline.version }}

- name: Create Skyline log directories
  action: file path={{ item }} state=directory
  with_items: [ /var/log/skyline, /var/run/skyline ]

- name: Install {{ skyline.path }}/requirements.txt with pip
  action: pip requirements={{ skyline.path }}/requirements.txt

- name: Install remaining dependencies with pip
  action: pip name={{ item.name }} version={{ item.version }}
  with_items:
  - { name: patsy, version: 0.2.1 }
  - { name: msgpack_python, version: 0.4.0 }

- name: Install python dependencies
  action: apt pkg={{ item.name }} state=installed
  with_items: 
  - { name: python-numpy }
  - { name: python-scipy }
  - { name: python-scikits.statsmodels }

- name: Update Skyline settings.py template
  template: src=settings.py.j2 dest={{ skyline.path }}/src/settings.py
  notify: 
  - restart skyline

- name: Symlink skyline init.d templates
  action: template src={{ item }}.j2 dest=/etc/init.d/{{ item }} mode=555 
  with_items: skyline.services
  notify: 
  - restart skyline

- name: start skyline 
  action: service name={{ item }} state=started
  with_items: skyline.services
